#测试环境配置
server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mjqzl
    username: root
    password: 898982009mjqzl
  mybatis:
    configuration:
      map-underscore-to-camel-case: true